/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms
*/
#include <stdio.h>

int next_fibonacci_number(int p, int q)
{
	return (p+q);
}

int main()
{
	int max_value = 4000000;
	int sum = 0;
	int fib_number = 0, p = 0, q = 1;
	while (fib_number < max_value) {
		fib_number = next_fibonacci_number(p, q);
		p = q;
		q = fib_number;
		if (q % 2 == 0)
			sum += q;
	}

	printf("Sum of the even-values fibonacci terms < %d is %d\n", max_value, sum);
}
